// Code generated by goyacc -o src/code/parser/parser.go src/code/parser/parser.go.y. DO NOT EDIT.

//line src/code/parser/parser.go.y:2
package parser

import __yyfmt__ "fmt"

//line src/code/parser/parser.go.y:2

import "github.com/macrat/simplexer"
import "strconv"
import "strings"
import "github.com/SIOS-Technology-Inc/dacrane/v0/src/code/ast"

func Parse(exprStr string) ast.Expr {
	lexer := NewLexer(strings.NewReader(exprStr))
	yyParse(lexer)
	return lexer.result
}

//line src/code/parser/parser.go.y:16
type yySymType struct {
	yys   int
	token *simplexer.Token
	expr  ast.Expr
	exprs []ast.Expr
	kvMap map[ast.Expr]ast.Expr
}

const IF = 57346
const THEN = 57347
const ELSE = 57348
const LSBRACKET = 57349
const RSBRACKET = 57350
const COMMA = 57351
const OR = 57352
const AND = 57353
const EQ = 57354
const NEQ = 57355
const LT = 57356
const LTE = 57357
const GT = 57358
const GTE = 57359
const NOT = 57360
const ADD = 57361
const SUB = 57362
const MUL = 57363
const DIV = 57364
const PRIORITY = 57365
const DOT = 57366
const UMINUS = 57367
const FLOAT = 57368
const INTEGER = 57369
const STRING = 57370
const BOOLEAN = 57371
const NULL = 57372
const IDENTIFIER = 57373
const COLON = 57374
const LBRACKET = 57375
const RBRACKET = 57376
const LCBRACKET = 57377
const RCBRACKET = 57378

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IF",
	"THEN",
	"ELSE",
	"LSBRACKET",
	"RSBRACKET",
	"COMMA",
	"OR",
	"AND",
	"EQ",
	"NEQ",
	"LT",
	"LTE",
	"GT",
	"GTE",
	"NOT",
	"ADD",
	"SUB",
	"MUL",
	"DIV",
	"PRIORITY",
	"DOT",
	"UMINUS",
	"FLOAT",
	"INTEGER",
	"STRING",
	"BOOLEAN",
	"NULL",
	"IDENTIFIER",
	"COLON",
	"LBRACKET",
	"RBRACKET",
	"LCBRACKET",
	"RCBRACKET",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line src/code/parser/parser.go.y:146

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 218

var yyAct = [...]int8{
	40, 2, 66, 41, 39, 43, 60, 36, 64, 34,
	35, 74, 29, 30, 22, 22, 37, 38, 13, 42,
	11, 44, 45, 46, 47, 48, 49, 50, 51, 52,
	53, 54, 55, 56, 57, 63, 73, 27, 28, 29,
	30, 22, 33, 10, 67, 32, 31, 20, 21, 23,
	24, 25, 26, 12, 27, 28, 29, 30, 22, 14,
	69, 61, 62, 1, 0, 42, 72, 70, 71, 58,
	9, 0, 0, 17, 0, 67, 77, 76, 0, 0,
	0, 0, 0, 0, 15, 0, 16, 0, 0, 0,
	0, 0, 3, 4, 5, 6, 7, 19, 0, 8,
	33, 18, 0, 32, 31, 20, 21, 23, 24, 25,
	26, 0, 27, 28, 29, 30, 22, 0, 0, 0,
	0, 0, 75, 33, 0, 65, 32, 31, 20, 21,
	23, 24, 25, 26, 0, 27, 28, 29, 30, 22,
	33, 68, 0, 32, 31, 20, 21, 23, 24, 25,
	26, 0, 27, 28, 29, 30, 22, 59, 0, 33,
	0, 0, 32, 31, 20, 21, 23, 24, 25, 26,
	0, 27, 28, 29, 30, 22, 33, 0, 0, 32,
	31, 20, 21, 23, 24, 25, 26, 0, 27, 28,
	29, 30, 22, 31, 20, 21, 23, 24, 25, 26,
	0, 27, 28, 29, 30, 22, 20, 21, 23, 24,
	25, 26, 0, 27, 28, 29, 30, 22,
}

var yyPact = [...]int16{
	66, -1000, 169, -1000, -1000, -1000, -1000, -1000, 66, 66,
	-1000, -1000, -1000, -1000, -17, 66, 66, 66, 66, -28,
	66, 66, 66, 66, 66, 66, 66, 66, 66, 66,
	66, 66, 66, 66, 35, 152, -25, 18, -1000, 53,
	169, -1, 93, 66, 18, 18, -1000, 18, 18, 18,
	18, -9, -9, -8, -8, 194, 182, 133, -1000, 66,
	-1000, -1000, 66, -1000, 66, 66, 2, 169, -1000, 116,
	-1000, -1000, 169, -1000, 66, 66, -1000, 169,
}

var yyPgo = [...]int8{
	0, 63, 0, 59, 53, 43, 20, 18, 2, 4,
	3,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 3,
	3, 7, 4, 8, 8, 8, 5, 9, 9, 9,
	6, 10, 10, 10,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 1, 1, 1, 3, 6, 1,
	1, 1, 1, 1, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 2, 2, 4,
	3, 1, 4, 3, 1, 0, 3, 3, 1, 0,
	3, 3, 3, 0,
}

var yyChk = [...]int16{
	-1000, -1, -2, 26, 27, 28, 29, 30, 33, 4,
	-5, -6, -4, -7, -3, 18, 20, 7, 35, 31,
	12, 13, 23, 14, 15, 16, 17, 19, 20, 21,
	22, 11, 10, 7, -2, -2, 24, -2, -2, -9,
	-2, -10, -2, 33, -2, -2, -2, -2, -2, -2,
	-2, -2, -2, -2, -2, -2, -2, -2, 34, 5,
	31, 8, 9, 36, 9, 32, -8, -2, 8, -2,
	-9, -10, -2, 34, 9, 6, -8, -2,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 3, 4, 5, 6, 0, 0,
	9, 10, 11, 12, 13, 0, 0, 39, 43, 31,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 27, 28, 0,
	38, 0, 0, 35, 14, 15, 16, 17, 18, 19,
	20, 21, 22, 23, 24, 25, 26, 0, 7, 0,
	30, 36, 39, 40, 43, 0, 0, 34, 29, 0,
	37, 41, 42, 32, 35, 0, 33, 8,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:52
		{
			yylex.(*Lexer).result = yyDollar[1].expr
			yyVAL.expr = yyDollar[1].expr
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:58
		{
			v, err := strconv.ParseFloat(yyDollar[1].token.Literal, 64)
			if err != nil {
				panic(err)
			}
			yyVAL.expr = &ast.SFloat{
				Value: v,
				Pos:   ast.PosFrom(&yyDollar[1].token.Position),
			}
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:68
		{
			v, err := strconv.Atoi(yyDollar[1].token.Literal)
			if err != nil {
				panic(err)
			}
			yyVAL.expr = &ast.SInteger{
				Value: v,
				Pos:   ast.PosFrom(&yyDollar[1].token.Position),
			}
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:78
		{
			yyVAL.expr = &ast.SString{
				Value: strings.Replace(yyDollar[1].token.Literal, "\"", "", -1),
				Pos:   ast.PosFrom(&yyDollar[1].token.Position),
			}
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:84
		{
			v, err := strconv.ParseBool(yyDollar[1].token.Literal)
			if err != nil {
				panic(err)
			}
			yyVAL.expr = &ast.SBool{
				Value: v,
				Pos:   ast.PosFrom(&yyDollar[1].token.Position),
			}
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:94
		{
			yyVAL.expr = &ast.SNull{Pos: ast.PosFrom(&yyDollar[1].token.Position)}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:95
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 8:
		yyDollar = yyS[yypt-6 : yypt+1]
//line src/code/parser/parser.go.y:96
		{
			yyVAL.expr = &ast.App{Func: "if", Args: []ast.Expr{yyDollar[4].expr, yyDollar[6].expr}}
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:97
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:98
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:99
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:100
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:101
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:102
		{
			yyVAL.expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].expr, yyDollar[3].expr}, Pos: yyDollar[1].expr.Position()}
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:103
		{
			yyVAL.expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].expr, yyDollar[3].expr}, Pos: yyDollar[1].expr.Position()}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:104
		{
			yyVAL.expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].expr, yyDollar[3].expr}, Pos: yyDollar[1].expr.Position()}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:105
		{
			yyVAL.expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].expr, yyDollar[3].expr}, Pos: yyDollar[1].expr.Position()}
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:106
		{
			yyVAL.expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].expr, yyDollar[3].expr}, Pos: yyDollar[1].expr.Position()}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:107
		{
			yyVAL.expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].expr, yyDollar[3].expr}, Pos: yyDollar[1].expr.Position()}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:108
		{
			yyVAL.expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].expr, yyDollar[3].expr}, Pos: yyDollar[1].expr.Position()}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:109
		{
			yyVAL.expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].expr, yyDollar[3].expr}, Pos: yyDollar[1].expr.Position()}
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:110
		{
			yyVAL.expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].expr, yyDollar[3].expr}, Pos: yyDollar[1].expr.Position()}
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:111
		{
			yyVAL.expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].expr, yyDollar[3].expr}, Pos: yyDollar[1].expr.Position()}
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:112
		{
			yyVAL.expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].expr, yyDollar[3].expr}, Pos: yyDollar[1].expr.Position()}
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:113
		{
			yyVAL.expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].expr, yyDollar[3].expr}, Pos: yyDollar[1].expr.Position()}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:114
		{
			yyVAL.expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].expr, yyDollar[3].expr}, Pos: yyDollar[1].expr.Position()}
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
//line src/code/parser/parser.go.y:115
		{
			yyVAL.expr = &ast.App{Func: yyDollar[1].token.Literal, Args: []ast.Expr{yyDollar[2].expr}, Pos: ast.PosFrom(&yyDollar[1].token.Position)}
		}
	case 28:
		yyDollar = yyS[yypt-2 : yypt+1]
//line src/code/parser/parser.go.y:116
		{
			yyVAL.expr = &ast.App{Func: yyDollar[1].token.Literal, Args: []ast.Expr{yyDollar[2].expr}, Pos: ast.PosFrom(&yyDollar[1].token.Position)}
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
//line src/code/parser/parser.go.y:120
		{
			yyVAL.expr = &ast.Ref{Dict: yyDollar[1].expr, Key: yyDollar[3].expr, Pos: yyDollar[1].expr.Position()}
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:121
		{
			yyVAL.expr = &ast.Ref{Dict: yyDollar[1].expr, Key: &ast.SString{Value: yyDollar[3].token.Literal, Pos: yyDollar[1].expr.Position()}}
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:123
		{
			yyVAL.expr = &ast.Variable{Name: yyDollar[1].token.Literal, Pos: ast.PosFrom(&yyDollar[1].token.Position)}
		}
	case 32:
		yyDollar = yyS[yypt-4 : yypt+1]
//line src/code/parser/parser.go.y:125
		{
			yyVAL.expr = &ast.App{Func: yyDollar[1].token.Literal, Args: yyDollar[3].exprs, Pos: ast.PosFrom(&yyDollar[1].token.Position)}
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:127
		{
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].exprs...)
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:128
		{
			yyVAL.exprs = []ast.Expr{yyDollar[1].expr}
		}
	case 35:
		yyDollar = yyS[yypt-0 : yypt+1]
//line src/code/parser/parser.go.y:129
		{
			yyVAL.exprs = []ast.Expr{}
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:131
		{
			yyVAL.expr = &ast.Seq{Value: yyDollar[2].exprs, Pos: ast.PosFrom(&yyDollar[1].token.Position)}
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:133
		{
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].exprs...)
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:134
		{
			yyVAL.exprs = []ast.Expr{yyDollar[1].expr}
		}
	case 39:
		yyDollar = yyS[yypt-0 : yypt+1]
//line src/code/parser/parser.go.y:135
		{
			yyVAL.exprs = []ast.Expr{}
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:137
		{
			yyVAL.expr = &ast.Map{Value: yyDollar[2].kvMap, Pos: ast.PosFrom(&yyDollar[1].token.Position)}
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:138
		{
			yyVAL.kvMap = yyDollar[1].kvMap
			for k, v := range yyDollar[3].kvMap {
				yyVAL.kvMap[k] = v
			}
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:144
		{
			yyVAL.kvMap = map[ast.Expr]ast.Expr{yyDollar[1].expr: yyDollar[3].expr}
		}
	case 43:
		yyDollar = yyS[yypt-0 : yypt+1]
//line src/code/parser/parser.go.y:145
		{
			yyVAL.kvMap = map[ast.Expr]ast.Expr{}
		}
	}
	goto yystack /* stack new state and value */
}
