// Code generated by goyacc -o src/code/parser/parser.go src/code/parser/parser.go.y. DO NOT EDIT.

//line src/code/parser/parser.go.y:2
package parser

import __yyfmt__ "fmt"

//line src/code/parser/parser.go.y:2

import "github.com/macrat/simplexer"
import "strconv"
import "strings"
import "github.com/SIOS-Technology-Inc/dacrane/v0/src/code/ast"

func Parse(exprStr string) ast.Module {
	lexer := NewLexer(strings.NewReader(exprStr))
	yyParse(lexer)
	return lexer.result
}

//line src/code/parser/parser.go.y:16
type yySymType struct {
	yys     int
	token   *simplexer.Token
	Module  ast.Module
	Expr    ast.Expr
	Exprs   []ast.Expr
	Params  []ast.Param
	KvMap   map[ast.Expr]ast.Expr
	String  string
	Strings []string
	Assigns []ast.Assign
}

const IF = 57346
const THEN = 57347
const ELSE = 57348
const LSBRACKET = 57349
const RSBRACKET = 57350
const COMMA = 57351
const OR = 57352
const AND = 57353
const EQ = 57354
const NEQ = 57355
const LT = 57356
const LTE = 57357
const GT = 57358
const GTE = 57359
const NOT = 57360
const ADD = 57361
const SUB = 57362
const MUL = 57363
const DIV = 57364
const PRIORITY = 57365
const DOT = 57366
const UMINUS = 57367
const FLOAT = 57368
const INTEGER = 57369
const STRING = 57370
const BOOLEAN = 57371
const NULL = 57372
const IDENTIFIER = 57373
const COLON = 57374
const LBRACKET = 57375
const RBRACKET = 57376
const LCBRACKET = 57377
const RCBRACKET = 57378
const FUNC = 57379
const DATA = 57380
const TYPE = 57381
const MODULE = 57382
const IMPORT = 57383
const EXPORT = 57384
const ASSIGN = 57385

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IF",
	"THEN",
	"ELSE",
	"LSBRACKET",
	"RSBRACKET",
	"COMMA",
	"OR",
	"AND",
	"EQ",
	"NEQ",
	"LT",
	"LTE",
	"GT",
	"GTE",
	"NOT",
	"ADD",
	"SUB",
	"MUL",
	"DIV",
	"PRIORITY",
	"DOT",
	"UMINUS",
	"FLOAT",
	"INTEGER",
	"STRING",
	"BOOLEAN",
	"NULL",
	"IDENTIFIER",
	"COLON",
	"LBRACKET",
	"RBRACKET",
	"LCBRACKET",
	"RCBRACKET",
	"FUNC",
	"DATA",
	"TYPE",
	"MODULE",
	"IMPORT",
	"EXPORT",
	"ASSIGN",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line src/code/parser/parser.go.y:198

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 244

var yyAct = [...]int8{
	57, 77, 58, 84, 16, 56, 49, 9, 6, 48,
	47, 37, 38, 39, 40, 41, 42, 17, 43, 44,
	45, 46, 4, 96, 50, 51, 82, 94, 60, 89,
	55, 53, 54, 74, 78, 59, 76, 11, 61, 62,
	63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
	73, 52, 93, 81, 88, 13, 7, 45, 46, 49,
	8, 85, 48, 47, 37, 38, 39, 40, 41, 42,
	10, 43, 44, 45, 46, 12, 87, 5, 24, 3,
	14, 33, 15, 59, 92, 91, 90, 28, 101, 79,
	80, 97, 30, 36, 31, 85, 99, 100, 98, 26,
	18, 19, 20, 21, 22, 35, 25, 23, 27, 34,
	49, 32, 29, 48, 47, 37, 38, 39, 40, 41,
	42, 2, 43, 44, 45, 46, 43, 44, 45, 46,
	1, 0, 0, 49, 0, 83, 48, 47, 37, 38,
	39, 40, 41, 42, 0, 43, 44, 45, 46, 0,
	0, 0, 0, 0, 95, 49, 0, 13, 48, 47,
	37, 38, 39, 40, 41, 42, 0, 43, 44, 45,
	46, 49, 86, 0, 48, 47, 37, 38, 39, 40,
	41, 42, 0, 43, 44, 45, 46, 75, 0, 49,
	0, 0, 48, 47, 37, 38, 39, 40, 41, 42,
	0, 43, 44, 45, 46, 49, 0, 0, 48, 47,
	37, 38, 39, 40, 41, 42, 0, 43, 44, 45,
	46, 47, 37, 38, 39, 40, 41, 42, 0, 43,
	44, 45, 46, 37, 38, 39, 40, 41, 42, 0,
	43, 44, 45, 46,
}

var yyPact = [...]int16{
	-18, -1000, -1000, -33, 25, -35, 6, -1000, 24, 6,
	-1000, 6, -1000, -39, -1000, -1000, 74, 126, -1000, -1000,
	-1000, -1000, -1000, 74, 74, -1000, -1000, -1000, -1000, 27,
	74, 74, -3, 74, 74, -5, -1000, 74, 74, 74,
	74, 74, 74, 74, 74, 74, 74, 74, 74, 74,
	-1, 182, 5, 107, -1000, 3, 81, 198, 17, 103,
	74, 107, 107, 107, 107, 107, 107, 36, 36, -1000,
	-1000, 221, 210, 164, -1000, 74, -1000, 20, -1000, -1000,
	74, -1000, 74, 74, 18, 198, -1000, 148, -12, 3,
	-1000, -1000, 198, -1000, 74, 74, 74, -1000, -1000, 198,
	52, -1000,
}

var yyPgo = [...]uint8{
	0, 130, 121, 0, 112, 108, 106, 99, 87, 3,
	5, 1, 2, 79, 70, 77, 60, 75,
}

var yyR1 = [...]int8{
	0, 1, 2, 13, 15, 15, 16, 16, 14, 14,
	17, 17, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
	4, 8, 11, 11, 11, 5, 9, 9, 9, 6,
	10, 10, 10, 7, 12, 12, 12,
}

var yyR2 = [...]int8{
	0, 1, 4, 2, 2, 0, 2, 0, 2, 0,
	4, 0, 1, 1, 1, 1, 1, 3, 6, 1,
	1, 1, 1, 1, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 2, 2, 7, 4,
	3, 1, 3, 1, 0, 4, 3, 1, 0, 3,
	3, 1, 0, 3, 3, 3, 0,
}

var yyChk = [...]int16{
	-1000, -1, -2, -13, 40, -15, 41, 31, -16, 42,
	-14, 31, -17, 31, -14, -14, 43, -3, 26, 27,
	28, 29, 30, 33, 4, -6, -7, -5, -8, -4,
	18, 20, 37, 7, 35, 31, -17, 12, 13, 14,
	15, 16, 17, 19, 20, 21, 22, 11, 10, 7,
	-3, -3, 24, -3, -3, 33, -10, -3, -12, -3,
	33, -3, -3, -3, -3, -3, -3, -3, -3, -3,
	-3, -3, -3, -3, 34, 5, 31, -11, 31, 8,
	9, 36, 9, 32, -9, -3, 8, -3, 34, 9,
	-10, -12, -3, 34, 9, 6, 35, -11, -9, -3,
	-3, 36,
}

var yyDef = [...]int8{
	0, -2, 1, 5, 0, 7, 9, 3, 11, 9,
	4, 9, 2, 0, 6, 8, 0, 11, 12, 13,
	14, 15, 16, 0, 0, 19, 20, 21, 22, 23,
	0, 0, 0, 52, 56, 41, 10, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 36, 37, 44, 0, 51, 0, 0,
	48, 24, 25, 26, 27, 28, 29, 30, 31, 32,
	33, 34, 35, 0, 17, 0, 40, 0, 43, 49,
	52, 53, 56, 0, 0, 47, 39, 0, 0, 44,
	50, 54, 55, 45, 48, 0, 0, 42, 46, 18,
	0, 38,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:63
		{
			yylex.(*Lexer).result = yyDollar[1].Module
			yyVAL.Module = yyDollar[1].Module
		}
	case 2:
		yyDollar = yyS[yypt-4 : yypt+1]
//line src/code/parser/parser.go.y:68
		{
			yyVAL.Module = ast.Module{
				Name:    yyDollar[1].String,
				Imports: yyDollar[2].Strings,
				Exports: yyDollar[3].Strings,
				Assigns: yyDollar[4].Assigns,
			}
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line src/code/parser/parser.go.y:77
		{
			yyVAL.String = yyDollar[2].token.Literal
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line src/code/parser/parser.go.y:80
		{
			yyVAL.Strings = yyDollar[2].Strings
		}
	case 5:
		yyDollar = yyS[yypt-0 : yypt+1]
//line src/code/parser/parser.go.y:81
		{
			yyVAL.Strings = []string{}
		}
	case 6:
		yyDollar = yyS[yypt-2 : yypt+1]
//line src/code/parser/parser.go.y:84
		{
			yyVAL.Strings = yyDollar[2].Strings
		}
	case 7:
		yyDollar = yyS[yypt-0 : yypt+1]
//line src/code/parser/parser.go.y:85
		{
			yyVAL.Strings = []string{}
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line src/code/parser/parser.go.y:88
		{
			yyVAL.Strings = append([]string{yyDollar[1].token.Literal}, yyDollar[2].Strings...)
		}
	case 9:
		yyDollar = yyS[yypt-0 : yypt+1]
//line src/code/parser/parser.go.y:89
		{
			yyVAL.Strings = []string{}
		}
	case 10:
		yyDollar = yyS[yypt-4 : yypt+1]
//line src/code/parser/parser.go.y:92
		{
			yyVAL.Assigns = append([]ast.Assign{{
				Name: yyDollar[1].token.Literal,
				Expr: yyDollar[3].Expr,
				Pos:  ast.PosFrom(&yyDollar[1].token.Position),
			}},
				yyDollar[4].Assigns...)
		}
	case 11:
		yyDollar = yyS[yypt-0 : yypt+1]
//line src/code/parser/parser.go.y:100
		{
			yyVAL.Assigns = []ast.Assign{}
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:103
		{
			v, err := strconv.ParseFloat(yyDollar[1].token.Literal, 64)
			if err != nil {
				panic(err)
			}
			yyVAL.Expr = &ast.SFloat{
				Value: v,
				Pos:   ast.PosFrom(&yyDollar[1].token.Position),
			}
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:113
		{
			v, err := strconv.Atoi(yyDollar[1].token.Literal)
			if err != nil {
				panic(err)
			}
			yyVAL.Expr = &ast.SInteger{
				Value: v,
				Pos:   ast.PosFrom(&yyDollar[1].token.Position),
			}
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:123
		{
			yyVAL.Expr = &ast.SString{
				Value: strings.Replace(yyDollar[1].token.Literal, "\"", "", -1),
				Pos:   ast.PosFrom(&yyDollar[1].token.Position),
			}
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:129
		{
			v, err := strconv.ParseBool(yyDollar[1].token.Literal)
			if err != nil {
				panic(err)
			}
			yyVAL.Expr = &ast.SBool{
				Value: v,
				Pos:   ast.PosFrom(&yyDollar[1].token.Position),
			}
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:139
		{
			yyVAL.Expr = &ast.SNull{Pos: ast.PosFrom(&yyDollar[1].token.Position)}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:140
		{
			yyVAL.Expr = yyDollar[2].Expr
		}
	case 18:
		yyDollar = yyS[yypt-6 : yypt+1]
//line src/code/parser/parser.go.y:141
		{
			yyVAL.Expr = &ast.App{Func: "if", Args: []ast.Expr{yyDollar[4].Expr, yyDollar[6].Expr}}
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:142
		{
			yyVAL.Expr = yyDollar[1].Expr
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:143
		{
			yyVAL.Expr = yyDollar[1].Expr
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:144
		{
			yyVAL.Expr = yyDollar[1].Expr
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:145
		{
			yyVAL.Expr = yyDollar[1].Expr
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:146
		{
			yyVAL.Expr = yyDollar[1].Expr
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:147
		{
			yyVAL.Expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].Expr, yyDollar[3].Expr}, Pos: yyDollar[1].Expr.Position()}
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:148
		{
			yyVAL.Expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].Expr, yyDollar[3].Expr}, Pos: yyDollar[1].Expr.Position()}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:149
		{
			yyVAL.Expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].Expr, yyDollar[3].Expr}, Pos: yyDollar[1].Expr.Position()}
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:150
		{
			yyVAL.Expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].Expr, yyDollar[3].Expr}, Pos: yyDollar[1].Expr.Position()}
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:151
		{
			yyVAL.Expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].Expr, yyDollar[3].Expr}, Pos: yyDollar[1].Expr.Position()}
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:152
		{
			yyVAL.Expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].Expr, yyDollar[3].Expr}, Pos: yyDollar[1].Expr.Position()}
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:153
		{
			yyVAL.Expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].Expr, yyDollar[3].Expr}, Pos: yyDollar[1].Expr.Position()}
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:154
		{
			yyVAL.Expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].Expr, yyDollar[3].Expr}, Pos: yyDollar[1].Expr.Position()}
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:155
		{
			yyVAL.Expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].Expr, yyDollar[3].Expr}, Pos: yyDollar[1].Expr.Position()}
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:156
		{
			yyVAL.Expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].Expr, yyDollar[3].Expr}, Pos: yyDollar[1].Expr.Position()}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:157
		{
			yyVAL.Expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].Expr, yyDollar[3].Expr}, Pos: yyDollar[1].Expr.Position()}
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:158
		{
			yyVAL.Expr = &ast.App{Func: yyDollar[2].token.Literal, Args: []ast.Expr{yyDollar[1].Expr, yyDollar[3].Expr}, Pos: yyDollar[1].Expr.Position()}
		}
	case 36:
		yyDollar = yyS[yypt-2 : yypt+1]
//line src/code/parser/parser.go.y:159
		{
			yyVAL.Expr = &ast.App{Func: yyDollar[1].token.Literal, Args: []ast.Expr{yyDollar[2].Expr}, Pos: ast.PosFrom(&yyDollar[1].token.Position)}
		}
	case 37:
		yyDollar = yyS[yypt-2 : yypt+1]
//line src/code/parser/parser.go.y:160
		{
			yyVAL.Expr = &ast.App{Func: yyDollar[1].token.Literal, Args: []ast.Expr{yyDollar[2].Expr}, Pos: ast.PosFrom(&yyDollar[1].token.Position)}
		}
	case 38:
		yyDollar = yyS[yypt-7 : yypt+1]
//line src/code/parser/parser.go.y:161
		{
			yyVAL.Expr = &ast.Func{Params: yyDollar[3].Params, Body: yyDollar[6].Expr, Pos: ast.PosFrom(&yyDollar[1].token.Position)}
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
//line src/code/parser/parser.go.y:167
		{
			yyVAL.Expr = &ast.Ref{Dict: yyDollar[1].Expr, Key: yyDollar[3].Expr, Pos: yyDollar[1].Expr.Position()}
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:168
		{
			yyVAL.Expr = &ast.Ref{Dict: yyDollar[1].Expr, Key: &ast.SString{Value: yyDollar[3].token.Literal, Pos: yyDollar[1].Expr.Position()}}
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:170
		{
			yyVAL.Expr = &ast.Variable{Name: yyDollar[1].token.Literal, Pos: ast.PosFrom(&yyDollar[1].token.Position)}
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:173
		{
			yyVAL.Params = append(yyDollar[1].Params, yyDollar[3].Params...)
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:174
		{
			yyVAL.Params = []ast.Param{{Name: yyDollar[1].token.Literal, Pos: ast.PosFrom(&yyDollar[1].token.Position)}}
		}
	case 44:
		yyDollar = yyS[yypt-0 : yypt+1]
//line src/code/parser/parser.go.y:175
		{
			yyVAL.Params = []ast.Param{}
		}
	case 45:
		yyDollar = yyS[yypt-4 : yypt+1]
//line src/code/parser/parser.go.y:177
		{
			yyVAL.Expr = &ast.App{Func: yyDollar[1].token.Literal, Args: yyDollar[3].Exprs, Pos: ast.PosFrom(&yyDollar[1].token.Position)}
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:179
		{
			yyVAL.Exprs = append(yyDollar[1].Exprs, yyDollar[3].Exprs...)
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:180
		{
			yyVAL.Exprs = []ast.Expr{yyDollar[1].Expr}
		}
	case 48:
		yyDollar = yyS[yypt-0 : yypt+1]
//line src/code/parser/parser.go.y:181
		{
			yyVAL.Exprs = []ast.Expr{}
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:183
		{
			yyVAL.Expr = &ast.Seq{Value: yyDollar[2].Exprs, Pos: ast.PosFrom(&yyDollar[1].token.Position)}
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:185
		{
			yyVAL.Exprs = append(yyDollar[1].Exprs, yyDollar[3].Exprs...)
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/code/parser/parser.go.y:186
		{
			yyVAL.Exprs = []ast.Expr{yyDollar[1].Expr}
		}
	case 52:
		yyDollar = yyS[yypt-0 : yypt+1]
//line src/code/parser/parser.go.y:187
		{
			yyVAL.Exprs = []ast.Expr{}
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:189
		{
			yyVAL.Expr = &ast.Map{Value: yyDollar[2].KvMap, Pos: ast.PosFrom(&yyDollar[1].token.Position)}
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:190
		{
			yyVAL.KvMap = yyDollar[1].KvMap
			for k, v := range yyDollar[3].KvMap {
				yyVAL.KvMap[k] = v
			}
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/code/parser/parser.go.y:196
		{
			yyVAL.KvMap = map[ast.Expr]ast.Expr{yyDollar[1].Expr: yyDollar[3].Expr}
		}
	case 56:
		yyDollar = yyS[yypt-0 : yypt+1]
//line src/code/parser/parser.go.y:197
		{
			yyVAL.KvMap = map[ast.Expr]ast.Expr{}
		}
	}
	goto yystack /* stack new state and value */
}
